policy:
  cherry-pick:
    upstream:
      - github: systemd/systemd
    exception:
      note:
        - rhel-only
        - RHEL-only
  tracker:
    - keyword:
        - 'Resolves: '
        - 'Related: '
        - 'Reverts: '
      type: jira
      issue-format:
        - 'RHEL-\d+$'
      url: 'https://issues.redhat.com/browse/'
