---
# SPDX-License-Identifier: LGPL-2.1-or-later
# Docs: https://packit.dev/docs/

specfile_path: .packit_rpm/systemd.spec
files_to_sync:
  - .packit.yml
  - src: .packit_rpm/systemd.spec
    dest: systemd.spec
upstream_package_name: systemd
downstream_package_name: systemd
# `git describe` returns in systemd's case 'v245-xxx' which breaks RPM version
# detection (that expects 245-xxxx'). Let's tweak the version string accordingly
upstream_tag_template: "v{version}"
srpm_build_deps: []

actions:
  get-current-version:
    # Show the closest matching tag for the checked out revision, otherwise
    # Packit tries to get the latest tag by creation date, which doesn't work
    # well in the systemd-stable repo. We also need to sanitize it manually
    # since "upstream_tag_template" defined above doesn't apply here.
    - "bash -ec 'git describe --tags --abbrev=0 | cut -b 2-'"

  post-upstream-clone:
    # Use the CentOS Stream 10 specfile
    # Pin this to the latest 10.1 version (systemd-257-13)
    - "git clone https://gitlab.com/redhat/centos-stream/rpms/systemd.git .packit_rpm --depth=1 --revision=8adcfa40b029b11bb2512c8cc7e6301ee3a77df9"
    # Drop the "sources" file so rebase-helper doesn't think we're a dist-git
    - "rm -fv .packit_rpm/sources"
    # Drop all patches, since they're already included in the tarball
    - "sed -ri '/^Patch[0-9]+:/d' .packit_rpm/systemd.spec"
    # Build the RPM with --werror. Even though --werror doesn't work in all
    # cases (see [0]), we can't use -Dc_args=/-Dcpp_args= here because of the
    # RPM hardening macros, that use $CFLAGS/$CPPFLAGS (see [1]).
    #
    # [0] https://github.com/mesonbuild/meson/issues/7360
    # [1] https://github.com/systemd/systemd/pull/18908#issuecomment-792250110
    - 'sed -i "/^CONFIGURE_OPTS=(/a--werror" .packit_rpm/systemd.spec'
    # Ignore unpackaged standalone binaries
    - "sed -i 's/assert False,.*/pass/' .packit_rpm/split-files.py"

# Available targets can be listed via `copr-cli list-chroots`
jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - centos-stream-10-aarch64
  - centos-stream-10-ppc64le
  - centos-stream-10-s390x
  - centos-stream-10-x86_64
