# doc: https://github.com/redhat-plumbers-in-action/devel-freezer#readme
---

name: Development Freeze
on:
  workflow_run:
    workflows: [ Gather Pull Request Metadata ]
    types:
      - completed

permissions:
  contents: read

jobs:
  freezer:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.repository == 'systemd/systemd'
    runs-on: ubuntu-22.04

    permissions:
      pull-requests: write

    steps:
      - id: artifact
        name: Download Pull Request Metadata artifact
        uses: redhat-plumbers-in-action/download-artifact@463ae626ac2dd333491c7beccaa24c12c5c259b8
        with:
          name: Pull Request Metadata

      - name: Repository checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
        with:
          fetch-depth: 0

      - name: Development Freezer
        uses: redhat-plumbers-in-action/devel-freezer@396c94ba8cb417474e6626c83a42addea210a403
        with:
          pr-number: ${{ fromJSON(steps.artifact.outputs.pr-metadata-json).number }}
          # delay start of validation to allow for some milestone/labels tweaking
          delay: 20
          token: ${{ secrets.GITHUB_TOKEN }}
